=== guilherme-webster/UniversitySpaceProblemOOP/src/XML/disciplines.dtd
<!ELEMENT disciplines (discipline+)>
<!ELEMENT discipline (disciplineName,disciplineId,credits,requiredSpaces,possibleInstitutes,professors)>
<!ELEMENT disciplineName (#PCDATA)>
<!ELEMENT disciplineId (#PCDATA)>
<!ELEMENT credits (#PCDATA)>
<!ELEMENT requiredSpaces (space+)>
<!ELEMENT space (#PCDATA)>
<!ELEMENT possibleInstitutes (institute+)>
<!ELEMENT institute (#PCDATA)>
<!ELEMENT professors (professor+)>
<!ELEMENT professor (#PCDATA)>

=== guilherme-webster/UniversitySpaceProblemOOP/src/XML/disciplines.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE disciplines SYSTEM "disciplines.dtd">

<disciplines>
    <discipline>
        <disciplineName> Cálculo I </disciplineName>
        <disciplineId> MA111 </disciplineId>
        <credits> 6 </credits>
        <requiredSpaces> 
            <space> BasicRoom </space>
            <space> BasicRoom </space>
            <space> SlidesRoom </space>
        </requiredSpaces>
        <possibleInstitutes>
            <institute> PB </institute>
            <institute> CB </institute>
        </possibleInstitutes>
        <professors>
            <professor>Leithold L. A. Alvarez</professor>
            <professor>Joerg D. W. Schleicher</professor>
        </professors>
    </discipline>

    <discipline>
        <disciplineName> Física Geral I </disciplineName>
        <disciplineId> F 128 </disciplineId>
        <credits> 4 </credits>
        <requiredSpaces> 
            <space> BasicRoom </space>
            <space> SlidesRoom </space>
        </requiredSpaces>
        <possibleInstitutes>
            <institute> PB </institute>
            <institute> CB </institute>
        </possibleInstitutes>
        <professors>
            <professor>José A. Brum</professor>
        </professors>
    </discipline>

    <discipline>
        <disciplineName> Geometria Analítica e Vetores </disciplineName>
        <disciplineId> MA141 </disciplineId>
        <credits> 4 </credits>
        <requiredSpaces> 
            <space> BasicRoom </space>
            <space> BasicRoom </space>
        </requiredSpaces>
        <possibleInstitutes>
            <institute> PB </institute>
            <institute> CB </institute>
        </possibleInstitutes>
        <professors>
            <professor>Eder M. Correa</professor>
        </professors>
    </discipline>

    <discipline>
        <disciplineName> Algoritmos e Programação de Computadores </disciplineName>
        <disciplineId> MC102 </disciplineId>
        <credits> 6 </credits>
        <requiredSpaces> 
            <space> SlidesRoom </space>
            <space> SlidesRoom </space>
            <space> ComputerRoom </space>
        </requiredSpaces>
        <possibleInstitutes>
            <institute> PB </institute>
            <institute> CB </institute>
            <institute> IC </institute>
        </possibleInstitutes>
        <professors>
            <professor>Rafael S. Schouery</professor>
        </professors>
    </discipline>

    <discipline>
        <disciplineName> Estrutura de Dados </disciplineName>
        <disciplineId> MC202 </disciplineId>
        <credits> 6 </credits>
        <requiredSpaces> 
            <space> SlidesRoom </space>
            <space> SlidesRoom </space>
            <space> ComputerRoom </space>
        </requiredSpaces>
        <possibleInstitutes>
            <institute> PB </institute>
            <institute> CB </institute>
            <institute> IC </institute>
        </possibleInstitutes>
        <professors>
            <professor>Guilherme P. Telles</professor>
        </professors>
    </discipline>

    <discipline>
        <disciplineName> Álgebra Linear </disciplineName>
        <disciplineId> MA327 </disciplineId>
        <credits> 4 </credits>
        <requiredSpaces> 
            <space> BasicRoom </space>
            <space> BasicRoom </space>
        </requiredSpaces>
        <possibleInstitutes>
            <institute> PB </institute>
            <institute> CB </institute>
        </possibleInstitutes>
        <professors>
            <professor>Eder M. Correa</professor>
        </professors>
    </discipline>

    <discipline>
        <disciplineName> Cálculo II </disciplineName>
        <disciplineId> MA211 </disciplineId>
        <credits> 6 </credits>
        <requiredSpaces> 
            <space> BasicRoom </space>
            <space> BasicRoom </space>
            <space> SlidesRoom </space>
        </requiredSpaces>
        <possibleInstitutes>
            <institute> PB </institute>
            <institute> CB </institute>
        </possibleInstitutes>
        <professors>
            <professor> Joachim Weber </professor>
            <professor>Claudemir F. B. Junior</professor>
        </professors>
    </discipline>

    <discipline>
        <disciplineName> Física Experimental I </disciplineName>
        <disciplineId> F 129 </disciplineId>
        <credits> 2 </credits>
        <requiredSpaces> 
            <space> PhysicsLaboratory </space>
        </requiredSpaces>
        <possibleInstitutes>
            <institute> IFGW </institute>
        </possibleInstitutes>
        <professors>
            <professor>Luiz F. C. Faria</professor>
        </professors>
    </discipline>

    <discipline>
        <disciplineName> Computação e Sociedade </disciplineName>
        <disciplineId> MC009 </disciplineId>
        <credits> 2 </credits>
        <requiredSpaces> 
            <space> Auditorium </space>
        </requiredSpaces>
        <possibleInstitutes>
            <institute> IC </institute>
        </possibleInstitutes>
        <professors>
            <professor>Claudia M. B. Medeiros</professor>
        </professors>
    </discipline>
    
    <discipline>
        <disciplineName> Cálculo III </disciplineName>
        <disciplineId> MA311 </disciplineId>
        <credits> 6 </credits>
        <requiredSpaces> 
            <space> BasicRoom </space>
            <space> BasicRoom </space>
            <space> SlidesRoom </space>
        </requiredSpaces>
        <possibleInstitutes>
            <institute> PB </institute>
            <institute> CB </institute>
        </possibleInstitutes>
        <professors>
            <professor>Lucas C.  F. Ferreira</professor>
        </professors>
    </discipline>

    <discipline>
        <disciplineName> Fundamentos Matemáticos da Computação </disciplineName>
        <disciplineId> MC358 </disciplineId>
        <credits> 4 </credits>
        <requiredSpaces> 
            <space> SlidesRoom </space>
            <space> SlidesRoom </space>
        </requiredSpaces>
        <possibleInstitutes>
            <institute> PB </institute>
            <institute> CB </institute>
        </possibleInstitutes>
        <professors>
            <professor>Pedro J.  Rezende</professor>
        </professors>
        </discipline>

    <discipline>
        <disciplineName> Programação Orientada a Objetos </disciplineName>
        <disciplineId> MC322 </disciplineId>
        <credits> 4 </credits>
        <requiredSpaces> 
            <space> SlidesRoom </space>
            <space> ComputerRoom </space>
        </requiredSpaces>
        <possibleInstitutes>
            <institute> PB </institute>
            <institute> CB </institute>
            <institute> IC </institute>
        </possibleInstitutes>
        <professors>
            <professor>Marcos M. Raimundo</professor>
        </professors>
    </discipline>

    <discipline>
        <disciplineName> Introdução aos Modelos Probabilísticos </disciplineName>
        <disciplineId> ME323 </disciplineId>
        <credits> 4 </credits>
        <requiredSpaces> 
            <space> BasicRoom </space>
            <space> BasicRoom </space>
        </requiredSpaces>
        <possibleInstitutes>
            <institute> PB </institute>
            <institute> CB </institute>
        </possibleInstitutes>
        <professors>
            <professor>Felipe A. Fernandes</professor>
        </professors>
    </discipline>

    <discipline>
        <disciplineName> Tópicos Especiais de Humanidades I </disciplineName>
        <disciplineId> HZ291 </disciplineId>
        <credits> 2 </credits>
        <requiredSpaces> 
            <space> SlidesRoom </space>
        </requiredSpaces>
        <possibleInstitutes>
            <institute> PB </institute>
            <institute> CB </institute>
        </possibleInstitutes>
        <professors>
            <professor>Pedro P. Ferreira</professor>
        </professors>
    </discipline>

    <discipline>
        <disciplineName> Química I </disciplineName>
        <disciplineId> QG101 </disciplineId>
        <credits> 4 </credits>
        <requiredSpaces> 
            <space> BasicRoom </space>
            <space> SlidesRoom </space>
        </requiredSpaces>
        <possibleInstitutes>
            <institute> PB </institute>
            <institute> CB </institute>
        </possibleInstitutes>
        <professors>
            <professor> Fabio Augusto </professor>
        </professors>
    </discipline>
    
    <discipline>
        <disciplineName> Física Geral II </disciplineName>
        <disciplineId> F 228 </disciplineId>
        <credits> 4 </credits>
        <requiredSpaces> 
            <space> BasicRoom </space>
            <space> SlidesRoom </space>
        </requiredSpaces>
        <possibleInstitutes>
            <institute> PB </institute>
            <institute> CB </institute>
        </possibleInstitutes>
        <professors>
            <professor> Diego Muraca </professor>
        </professors>
    </discipline>

    <discipline>
        <disciplineName> Física Experimental II </disciplineName>
        <disciplineId> F 229 </disciplineId>
        <credits> 2 </credits>
        <requiredSpaces> 
            <space> PhysicsLaboratory </space>
        </requiredSpaces>
        <possibleInstitutes>
            <institute> IFGW </institute>
        </possibleInstitutes>
        <professors>
            <professor>Natalia  F. Coutinho</professor>
        </professors>
    </discipline>

    <discipline>
        <disciplineName> Inglês Instrumental I </disciplineName>
        <disciplineId> LA122 </disciplineId>
        <credits> 4 </credits>
        <requiredSpaces> 
            <space> SlidesRoom </space>
            <space> SlidesRoom </space>
        </requiredSpaces>
        <possibleInstitutes>
            <institute> PB </institute>
            <institute> CB </institute>
        </possibleInstitutes>
        <professors>
